// react/src/components/Header.jsx
import { useState } from 'react';
import { RouterLink } from './RouterLink';

const navigation = [
  { href: '/', label: 'Home' },
  { href: '/categories', label: 'Menu' },
  { href: '/about', label: 'Our story' },
  { href: '/contact', label: 'Visit us' }
];

export function Header({ currentPath, onNavigate }) {
  const [menuOpen, setMenuOpen] = useState(false);

  function navigate(path) {
    setMenuOpen(false);
    onNavigate(path);
  }

  return (
    <header className="site-header">
      <div className="shell header-inner">
        <RouterLink className="brand" href="/" onNavigate={navigate} aria-label="De Origen home">
          <span className="brand-mark" aria-hidden="true">D</span>
          <span><strong>DE ORIGEN</strong><small>COFFEE ROASTERS</small></span>
        </RouterLink>
        <button className="menu-button" type="button" aria-expanded={menuOpen} aria-controls="primary-navigation" onClick={() => setMenuOpen((open) => !open)}>
          <span className="sr-only">Toggle navigation</span>
          <span aria-hidden="true">{menuOpen ? 'Close' : 'Menu'}</span>
        </button>
        <nav id="primary-navigation" className={menuOpen ? 'navigation is-open' : 'navigation'} aria-label="Primary navigation">
          {navigation.map((item) => (
            <RouterLink key={item.href} href={item.href} onNavigate={navigate} aria-current={currentPath === item.href ? 'page' : undefined}>
              {item.label}
            </RouterLink>
          ))}
        </nav>
        <RouterLink className="button button-small header-cta" href="/contact" onNavigate={navigate}>Find the shop</RouterLink>
      </div>
    </header>
  );
}

// angular/src/app/components/header.component.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  imports: [RouterLink, RouterLinkActive],
  template: `
    <header class="site-header">
      <div class="shell header-inner">
        <a class="brand" routerLink="/" aria-label="De Origen home" (click)="closeMenu()">
          <span class="brand-mark" aria-hidden="true">D</span>
          <span><strong>DE ORIGEN</strong><small>COFFEE ROASTERS</small></span>
        </a>
        <button class="menu-button" type="button" [attr.aria-expanded]="menuOpen()" aria-controls="primary-navigation" (click)="toggleMenu()">
          <span class="sr-only">Toggle navigation</span><span aria-hidden="true">{{ menuOpen() ? 'Close' : 'Menu' }}</span>
        </button>
        <nav id="primary-navigation" class="navigation" [class.is-open]="menuOpen()" aria-label="Primary navigation">
          @for (item of navigation; track item.path) {
            <a [routerLink]="item.path" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: item.path === '/' }" (click)="closeMenu()">{{ item.label }}</a>
          }
        </nav>
        <a class="button button-small header-cta" routerLink="/contact">Find the shop</a>
      </div>
    </header>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HeaderComponent {
  protected readonly menuOpen = signal(false);
  protected readonly navigation = [
    { path: '/', label: 'Home' },
    { path: '/categories', label: 'Menu' },
    { path: '/about', label: 'Our story' },
    { path: '/contact', label: 'Visit us' }
  ] as const;

  protected toggleMenu(): void { this.menuOpen.update((open) => !open); }
  protected closeMenu(): void { this.menuOpen.set(false); }
}
