// react/src/components/PageHero.jsx
export function PageHero({ eyebrow, title, children }) {
  return (
    <section className="page-hero">
      <div className="shell narrow">
        <p className="eyebrow">{eyebrow}</p>
        <h1>{title}</h1>
        {children && <p className="page-intro">{children}</p>}
      </div>
    </section>
  );
}

// angular/src/app/components/page-hero.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

@Component({
  selector: 'app-page-hero',
  template: `<section class="page-hero"><div class="shell narrow"><p class="eyebrow">{{ eyebrow() }}</p><h1>{{ title() }}</h1><p class="page-intro"><ng-content /></p></div></section>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PageHeroComponent {
  readonly eyebrow = input.required<string>();
  readonly title = input.required<string>();
}
